blog/urls.py
from django.urls import path
from . import views

app_name="blog"

urlpatterns = [
    path('', views.articles, name="articles_list"),
    path('articles/article-'+'<id>', views.article_detail,name="article_detail"),
]


"""import easyocr
f='assets/images/CG-RECTO.PNG'
reader=easyocr.Reader(['fr','ar','en'],gpu=False)
results=reader.readtext(f)


text=''
for result in results:
    text += result[1]+' ** '

print(text)

nation = [match for match in results if "SENEGALAISE" in match[1]]

print(nation)"""

testdjango/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path(r"test/", views.test),
    path(r'', views.index),
    path('blog/', include('blog.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

# Create your models here.

class Article(models.Model):
    title = models.CharField(max_length=30)
    body = models.TextField()
    author = models.CharField(max_length=50)
    date = models.DateField()
    image=models.ImageField(blank=True,default='default.png')

    def __str__(self):
        return self.title

    def snippet(self):
        return self.body[:30]+'...'

class Comment(models.Model):
    content = models.TextField()    
    date = models.DateField()
    article = models.ForeignKey(Article, on_delete=models.CASCADE)

    def __str__(self):
        return self.content

blog/views.py
from blog.models import Article
from django.shortcuts import render
import cv2
import easyocr
try:
    from PIL import Image
except ImportError:
    import Image

import pytesseract
from pytesseract import Output



def article_detail(request,id):
    article=Article.objects.get(id=id)
    return render(request,'blog/detail.html',{'article':article})


def articles(request):
    articles=Article.objects.all().order_by('date')  
     """f='assets/images/CG-RECTO.PNG'
    reader=easyocr.Reader(lang_list=["ar","fa","ur","ug","en"],gpu=True)
    results=reader.readtext(f)
    
    text=''
    for result in results:
        print(result)"""

      

    img=cv2.imread('./assets/images/CG-RECTO.PNG')
    img=cv2.cvtColor(img,cv2.COLOR_HLS2RGB)
    print(pytesseract.image_to_string(img))
    cv2.imshow('Result',img)

    cv2.waitKey(0)
    return render(request,'blog/list.html',{'articles':articles})

testdjango/views.py
from django.shortcuts import render

def index(request):
    return render(request,'index.html')


def test(request):
    return render(request,'test.html')

blog/templates/blog/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1 class>Articles details </h1>
</body>
</html>

blog/templates/blog/list.html
{% extends 'layout.html' %}
{% load static %}

{% block content %}
    <img class="w-1/5" src="{% static 'images/sejour.jpeg' %}" alt="" srcset="">
    <h1>List des articles</h1>    
    <div class="articles">
        {% for article in articles %}
        <div class="bg-gray-200">
            <h1>{{article.title}}</h1>
            <p>
                <img src="{{article.image.url}}" alt="img" srcset=""><br>
                {{article.snippet}}<br>
                <span>{{article.date}}</span><br>
                <a class="text-white font-bold bg-red-300 px-2 py-1 rounded-md " href="{% url 'blog:article_detail' id=article.id %}">voir plus</a>
            </p>
        </div>
        {% endfor%}
    </div>
{% endblock %}

templates/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static '/css/style.min.css' %}">
    <title>Django test</title>
</head>
<body>
    <div class="container mx-auto bg-gray-100">
        {% block content %}
        {% endblock %}
    </div>    
</body>
</html>

templates/test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h2>Test Django page</h2>
</body>
</html>

testdjango/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Page d'accueil page</h1>
</body>
</html>

testdjango/templates/test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h2>Test Django page</h2>
</body>
</html>